image: python:3.8
pipelines:
  pull-requests:
    "**":
      - step:
          name: unit testing
          size: 1x
          script:
            - JFROG_BOT_USERNAME=$JFROG_BOT_USERNAME JFROG_BOT_PASS=$JFROG_BOT_PASS python setup.py install
          trigger: automatic
  branches:
    master: &shared
      - step:
          name: upload library to jfrog
          script:
            - printf "[distutils]\n" >> ~/.pypirc
            - printf "index-servers=splighthub\n" >> ~/.pypirc
            - printf "[splighthub]\n" >> ~/.pypirc
            - printf "repository:https://splight.jfrog.io/artifactory/api/pypi/splight-local\n" >> ~/.pypirc
            - printf "username=$JFROG_BOT_USERNAME\n" >> ~/.pypirc
            - printf "password=$JFROG_BOT_PASS" >> ~/.pypirc
            - python setup.py bdist_wheel upload -r splighthub
            - rm ~/.pypirc;
    main: *shared
