version: "3.3"
services:
  runner:
    image: splight-runner:latest
    build:
      context: .
      args:
        - JFROG_BOT_USERNAME=$JFROG_BOT_USERNAME
        - JFROG_BOT_PASS=$JFROG_BOT_PASS
        - VERSION=$VERSION
    command: bash
    env_file: ./env_file
    tty: true
    volumes:
      - .:/code
