name: Code Quality
on: pull_request
jobs:
  black:
    runs-on: ubuntu-latest
    name: Black
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --diff"
          version: "23.1.0"
  isort:
    runs-on: ubuntu-latest
    name: Isort
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@master
        with:
          configuration: "--check-only --diff"
          isortVersion: "5.12.0"
  run_snyk:
    runs-on: ubuntu-latest
    name: Check for vulnerabilities using Snyk
    steps:
      - uses: actions/checkout@v3
      - name: Install Snyk
        run: npm install snyk -g
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_API_KEY }}
      - name: Check Vulnerabilities
        run: |
          snyk code test
          snyk test
