name: Runner-Builder-Dev

on: workflow_dispatch

env:
  LIBRARY_NAME: "splight-cli"

jobs:
  verify_version:
    runs-on: ubuntu-latest
    name: Verify dev Splight CLI version
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3
      - name: Get version from feature branch
        run: echo "CURRENT_VERSION=$(python setup.py --version)" >> "$GITHUB_ENV"
      # validate versions
      - name: Valida dev version
        run: python3 .github/workflows/scripts/check_dev_version.py ${{ env.CURRENT_VERSION }}

  upload_builder_image:
    runs-on: ubuntu-latest
    name: Push Builder image to ECR
    needs: [verify_version]
    steps:
      - name: Checkout to feature branch
        uses: action/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push builder image
        working-directory: .
        run: |
          export VERSION=$(python setup.py --version)
          GITHUB_TOKEN=$GITHUB_TOKEN AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} docker-compose -f builder/docker-compose.yml build
          docker tag splight-builder $AWS_ECR/splight-jobs:builder-${VERSION}
          docker push $AWS_ECR/splight-jobs:builder-${VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
          AWS_ECR: ${{ secrets.AWS_ECR }}

  upload_runner_image:
    runs-on: ubuntu-latest
    name: Push Runner image to ECR
    needs: [verify_version]
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push runner image
        working-directory: .
        run: |
          export VERSION=$(python setup.py --version)
          VERSION=$VERSION docker-compose -f runner/docker-compose.yml build
          docker tag splight-runner $AWS_ECR/splight-runner:${VERSION}
          docker push $AWS_ECR/splight-runner:${VERSION}
        env:
          AWS_ECR: ${{secrets.AWS_ECR}}
