name: "Running Tests"
on:
  pull_request:
    types:
      [opened, synchronize]
    branches:
      - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    name: running tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: make install
      - run: make test
