name: "Running Tests"
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - firstgha
jobs:
  tests:
    runs-on: ubuntu-latest
    name: running tests
    env:
      JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
      JFROG_PASS: ${{secrets.JFROG_PASS}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: printf "[distutils]\n" >> ~/.pypirc
      - run: printf "index-servers=splightlib\n" >> ~/.pypirc
      - run: printf "[splightlib]\n" >> ~/.pypirc
      - run: printf "repository:https://splight.jfrog.io/artifactory/api/pypi/splight-local\n" >> ~/.pypirc
      - run: printf "username=$JFROG_USERNAME\n" >> ~/.pypirc
      - run: printf "password=$JFROG_PASS" >> ~/.pypirc
      - run: pip install -r requirements.txt
      - run: sudo python setup.py install
      - run: sudo pytest .