name: Push ECR image
on:
  push:
    branches:
      - integration
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    name: push image to registry
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push image
        working-directory: ./runner
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [[ $BRANCH == "integration" ]]; then export TAG="integration"; fi
          JFROG_BOT_USERNAME=$JFROG_USERNAME JFROG_BOT_PASS=$JFROG_PASS docker-compose build
          docker tag splight-runner:latest $AWS_ECR/splight-runner:${TAG:-latest}
          docker push $AWS_ECR/splight-runner:${TAG:-latest}
        env:
          JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
          JFROG_PASS: ${{secrets.JFROG_PASS}}
          AWS_ECR: ${{secrets.AWS_ECR}}
