name: Push runner image to ECR
on:
  push:
    branches:
      - integration
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    name: push image to registry
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push runner image
        working-directory: .
        run: |
          export VERSION=$(python setup.py --version)
          export BRANCH=${GITHUB_REF##*/}
          if [ ${BRANCH} = "master" ]; then export TAG="production"; else export TAG="integration"; fi;
          VERSION=$VERSION docker-compose -f runner/docker-compose.yml build
          docker tag splight-runner $AWS_ECR/splight-runner:${TAG}-${VERSION}
          docker push $AWS_ECR/splight-runner:${TAG}-${VERSION}
        env:
          AWS_ECR: ${{secrets.AWS_ECR}}
