name: Push builder image to ECR
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    name: push image to registry
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push builder image
        working-directory: .
        run: |
          export VERSION=$(python setup.py --version)
          GITHUB_TOKEN=$GITHUB_TOKEN AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} docker-compose -f builder/docker-compose.yml build
          docker tag splight-builder $AWS_ECR/splight-jobs:builder-${VERSION}
          docker push $AWS_ECR/splight-jobs:builder-${VERSION}
        env:
          GITHUB_TOKEN: ${{secrets.APP_GITHUB_TOKEN}}
          AWS_ECR: ${{secrets.AWS_ECR}}
